"""Pydantic schema for the portfolio's `prefect.yaml`.

Pinned shape: all StatDeskAU scrapers use the same pull-step pattern and
the same `work_pool: default`. New scrapers generated by
`cookiecutter-statdesk-scraper` produce a YAML that satisfies this
schema by construction. Existing scrapers (SQM, NSW VG, Scraper_0062)
also conform.

Pre-flight runs this validator and rejects deploys whose YAML drifts.
"""
from __future__ import annotations

from typing import Any, Literal

import yaml
from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator


# --------------------------------------------------------------------------
# Pull steps
# --------------------------------------------------------------------------

class GitCloneStep(BaseModel):
    """`prefect.deployments.steps.git_clone` step in the pull chain."""

    model_config = ConfigDict(extra="forbid")

    id: str = "clone"
    repository: str
    branch: str
    access_token: str  # must reference the github-pat Secret block

    @field_validator("access_token")
    @classmethod
    def _must_reference_secret(cls, v: str) -> str:
        if "prefect.blocks.secret" not in v:
            raise ValueError(
                "access_token must reference a Prefect Secret block, "
                "e.g. '{{ prefect.blocks.secret.github-pat }}'"
            )
        return v


class RunShellScriptStep(BaseModel):
    """`prefect.deployments.steps.run_shell_script` step (pip install, import verify)."""

    model_config = ConfigDict(extra="forbid")

    id: str | None = None
    script: str
    directory: str | None = None


# Each pull-step entry in YAML is `{<step_qualname>: {...}}`. We model it
# as a single-key dict with a discriminated value.
class PullStepEntry(BaseModel):
    model_config = ConfigDict(extra="forbid")

    git_clone: GitCloneStep | None = Field(default=None, alias="prefect.deployments.steps.git_clone")
    run_shell_script: RunShellScriptStep | None = Field(default=None, alias="prefect.deployments.steps.run_shell_script")

    @field_validator("git_clone", "run_shell_script", mode="before")
    @classmethod
    def _none_is_ok(cls, v: Any) -> Any:
        return v


# --------------------------------------------------------------------------
# Deployments
# --------------------------------------------------------------------------

class Schedule(BaseModel):
    """A deployment schedule (cron or rrule)."""

    model_config = ConfigDict(extra="forbid")

    cron: str | None = None
    rrule: str | None = None
    timezone: str = "UTC"

    @field_validator("cron", "rrule", mode="after")
    @classmethod
    def _at_least_one(cls, v, info):
        # validation across both happens in the model-level check below
        return v


class JobVariablesEnv(BaseModel):
    """Per-deployment env vars injected into the flow-run subprocess.

    Must include PGDATABASE so the worker knows which DB on
    scraperportfoliopg to talk to (worker env provides PGHOST/PORT/USER/
    PASSWORD; the deployment provides only the DB name).
    """

    model_config = ConfigDict(extra="allow")

    PGDATABASE: str


class JobVariables(BaseModel):
    model_config = ConfigDict(extra="allow")

    env: JobVariablesEnv


class WorkPool(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: Literal["default"]


class Deployment(BaseModel):
    """One deployment declared in `prefect.yaml`."""

    model_config = ConfigDict(extra="allow")

    name: str
    entrypoint: str
    work_pool: WorkPool
    tags: list[str] = Field(default_factory=list)
    concurrency_limit: int = 1
    paused: bool = True
    schedule: Schedule | None = None
    job_variables: JobVariables

    @field_validator("entrypoint")
    @classmethod
    def _entrypoint_shape(cls, v: str) -> str:
        # entrypoint is "path/to/file.py:function_name"
        if ":" not in v:
            raise ValueError(
                "entrypoint must be of the form '<path>:<function>' "
                "(e.g. 'pipeline_flow.py:my_flow')"
            )
        return v


# --------------------------------------------------------------------------
# Top-level prefect.yaml
# --------------------------------------------------------------------------

class PrefectYaml(BaseModel):
    """The portfolio-shape `prefect.yaml`.

    Top-level keys recognised: name, prefect-version, pull, deployments.
    Other keys (e.g. `definitions`) are tolerated via `extra="allow"`.
    """

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str
    prefect_version: str = Field(alias="prefect-version", default="3.x")
    pull: list[dict[str, Any]]
    deployments: list[Deployment]

    @field_validator("pull")
    @classmethod
    def _pull_has_git_clone_then_pip(cls, v: list[dict[str, Any]]) -> list[dict[str, Any]]:
        if not v:
            raise ValueError("pull steps cannot be empty")
        # First step must be git_clone
        first_key = next(iter(v[0]))
        if first_key != "prefect.deployments.steps.git_clone":
            raise ValueError(
                f"First pull step must be prefect.deployments.steps.git_clone, "
                f"got {first_key!r}"
            )
        # Construct typed inner-step models so their own validators run
        # (notably GitCloneStep's access_token must-reference-secret-block check).
        for step in v:
            for key, body in step.items():
                if key == "prefect.deployments.steps.git_clone":
                    GitCloneStep.model_validate(body)
                elif key == "prefect.deployments.steps.run_shell_script":
                    RunShellScriptStep.model_validate(body)
        # Must include at least one pip install run_shell_script
        has_pip = any(
            "prefect.deployments.steps.run_shell_script" in step
            and "pip install" in (step["prefect.deployments.steps.run_shell_script"].get("script") or "")
            for step in v
        )
        if not has_pip:
            raise ValueError(
                "pull steps must include a `pip install` run_shell_script "
                "so the package is importable in the worker's system Python"
            )
        return v


def parse_prefect_yaml(text: str) -> PrefectYaml:
    """Parse `prefect.yaml` text into the validated model.

    Raises pydantic.ValidationError on schema violations.
    """
    raw = yaml.safe_load(text) or {}
    return PrefectYaml.model_validate(raw)


__all__ = ["PrefectYaml", "Deployment", "Schedule", "parse_prefect_yaml", "ValidationError"]
